#!/bin/bash

cd mockup
qmake eyetracker-mockup.pro
make -j4
cd ..

cd camera
qmake eyetracker-hpe.pro
make -j4
cd ..

cd ml
qmake eyetracker-ml.pro
make -j4
cd ..

if [ -f tobii/sdk/include/tobiigaze.h ]; then
    cd tobii
    qmake eyetracker-tobii.pro
    make -j4
    cd ..
else
    echo No Tobii Gaze SDK detected.
fi

mkdir -p bin

cp mockup/eyetracker-mockup bin/eyetracker-mockup
cp camera/eyetracker-hpe bin/eyetracker-hpe
cp ml/eyetracker-ml bin/eyetracker-ml

if [ -f tobii/eyetracker-tobii ]; then
    cp tobii/eyetracker-tobii bin/eyetracker-tobii
fi

