#!/bin/bash

cd mockup
qmake pisak-eyetracker-mockup.pro
make -j4
cd ..

cd camera
qmake pisak-eyetracker-hpe.pro
make -j4
cd ..

cd ml
qmake pisak-eyetracker-ml.pro
make -j4
cd ..

cd tobii
qmake pisak-eyetracker-tobii.pro
make -j4
cd ..

mkdir -p bin

cp mockup/pisak-eyetracker-mockup bin/pisak-eyetracker-mockup
cp camera/pisak-eyetracker-hpe bin/pisak-eyetracker-hpe
cp ml/pisak-eyetracker-ml bin/pisak-eyetracker-ml
cp tobii/pisak-eyetracker-tobii bin/pisak-eyetracker-tobii

